export const mockRequests = [
  {
    call_id: 'CALL-1001',
    timestamp: '2026-04-29T15:30:00Z',
    caller_phone: '(478) 555-0141',
    caller_name: 'Helen Brooks',
    call_type: 'appointment_request',
    service_type: 'Real Estate Closing',
    document_type: 'Deed',
    location_address: '124 Willow Drive, Macon, GA',
    preferred_date: '2026-05-02',
    preferred_time: '10:30 AM',
    urgency: 'high',
    needs_michael_callback: true,
    missing_info: 'Needs alternate signer phone number.',
    call_summary: 'Client needs a same-day confirmation for a closing packet.',
    price_mentioned: true,
    quoted_price: 175,
    confidence_score: 0.92,
    call_status: 'new',
  },
  {
    call_id: 'CALL-1002',
    timestamp: '2026-04-29T17:05:00Z',
    caller_phone: '(478) 555-0148',
    caller_name: 'James Porter',
    call_type: 'pricing_question',
    service_type: 'Power of Attorney',
    document_type: 'POA',
    location_address: '890 Ridge Ave, Warner Robins, GA',
    preferred_date: '2026-05-03',
    preferred_time: '1:00 PM',
    urgency: 'medium',
    needs_michael_callback: false,
    missing_info: '',
    call_summary: 'Caller asked about pricing and travel fees for POA notarization.',
    price_mentioned: true,
    quoted_price: 95,
    confidence_score: 0.88,
    call_status: 'called',
  },
  {
    call_id: 'CALL-1003',
    timestamp: '2026-04-30T09:12:00Z',
    caller_phone: '(478) 555-0199',
    caller_name: 'Donna Fields',
    call_type: 'appointment_request',
    service_type: 'Hospital Notarization',
    document_type: 'Medical Directive',
    location_address: 'Mercy Hospital, Macon, GA',
    preferred_date: '2026-05-01',
    preferred_time: '9:15 AM',
    urgency: 'urgent',
    needs_michael_callback: true,
    missing_info: 'Needs room number before arrival.',
    call_summary: 'Family requested urgent in-hospital notarization support.',
    price_mentioned: false,
    quoted_price: 0,
    confidence_score: 0.94,
    call_status: 'pending',
  },
]

export const mockMetrics = {
  totalCalls: 38,
  totalMinutes: 126,
  totalCost: 421.5,
  appointmentRequests: 19,
  pricingQuestions: 8,
  availabilityQuestions: 4,
  generalQuestions: 5,
  spamFiltered: 2,
  needsCallback: 7,
  approvedRequests: 11,
  deniedRequests: 3,
  averageHandleTime: 3.3,
  costPerLead: 22.18,
}

export const mockDetail = {
  success: true,
  call_id: 'CALL-1001',
  call: mockRequests[0],
  transcript:
    'Caller stated they need a deed notarized for a closing and asked for a callback before 4 PM today. They provided address and preferred morning slot.',
  recording_url: '',
}
